language: java
sudo: required
install: true
jdk:
  - oraclejdk8

addons:
    apt:
    packages:
    - oracle-java8-installer
    
cache:
    directories:
    - $HOME/.m2

script: 
    - cd backend
    - ./mvnw clean install